version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./my-netacho-api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./my-netacho-api:/var/www
  front:
    build: ./docker/next
    working_dir: /app
    tty: true
    volumes:
      - ./my-netacho-front:/app
    command: bash -c 'yarn install && yarn dev'
    ports:
      - 3000:3000
  mysql:
    platform: linux/amd64
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306